apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: telemarkfylke-no

resources:
  - ../../../base

commonLabels:
  app.kubernetes.io/instance: fint-flyt-egrunnerverv-dispatch-gateway_telemarkfylke_no
  fintlabs.no/org-id: telemarkfylke.no

patches:
  - patch: |-
      - op: replace
        path: "/spec/kafka/acls/0/topic"
        value: "telemarkfylke-no.flyt.*"
      - op: replace
        path: "/spec/orgId"
        value: "telemarkfylke.no"
      - op: replace
        path: "/spec/env/1/value"
        value: "https://vigoikstest.service-now.com/api/now/table"
      - op: replace
        path: "/spec/env/2/value"
        value: "https://vigoikstest.service-now.com/oauth_token.do"
      - op: replace
        path: "/spec/onePassword/itemPath"
        value: "vaults/aks-beta-vault/items/fint-flyt-egrunnerverv-dispatch-gateway-out"
      - op: add
        path: "/spec/env/-"
        value:
          name: "logging.level.no.fintlabs"
          value: "DEBUG"
    target:
      kind: Application
      name: fint-flyt-egrunnerverv-dispatch-gateway

